// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwCLcDzWvy3258qcCxFcYJb8f-r3Zl8ng',
    appId: '1:987937327476:web:0db850087dbd480a62c421',
    messagingSenderId: '987937327476',
    projectId: 'smart-check-923da',
    authDomain: 'smart-check-923da.firebaseapp.com',
    storageBucket: 'smart-check-923da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD58xxVOFeX6d642UxchQBh2zDuK0wjbTg',
    appId: '1:987937327476:android:e718863cd8d5c84062c421',
    messagingSenderId: '987937327476',
    projectId: 'smart-check-923da',
    storageBucket: 'smart-check-923da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqvXnN1XrIpmvJ_fBlf27CR0h3KLywFI',
    appId: '1:987937327476:ios:a0cf91ebebc82bcc62c421',
    messagingSenderId: '987937327476',
    projectId: 'smart-check-923da',
    storageBucket: 'smart-check-923da.firebasestorage.app',
    iosBundleId: 'com.example.smartCheck',
  );
}
